// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbVNAOqPVcxXsrIAEer-h4GeTLigl2nx0',
    appId: '1:943448413343:web:2d856c25eb77e71ffbfeaa',
    messagingSenderId: '943448413343',
    projectId: 'assignment-3-641c4',
    authDomain: 'assignment-3-641c4.firebaseapp.com',
    storageBucket: 'assignment-3-641c4.appspot.com',
    measurementId: 'G-7G0KKZTLTL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjMmic2g8ptUAH8fwAyiISi0AGgVThDU0',
    appId: '1:943448413343:android:a71e25e180382898fbfeaa',
    messagingSenderId: '943448413343',
    projectId: 'assignment-3-641c4',
    storageBucket: 'assignment-3-641c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsNsurUFowQuuaakmKzoxzLVFoeJyHi-E',
    appId: '1:943448413343:ios:b52e68a193bade9dfbfeaa',
    messagingSenderId: '943448413343',
    projectId: 'assignment-3-641c4',
    storageBucket: 'assignment-3-641c4.appspot.com',
    iosClientId: '943448413343-qt97stqcav5eflsn6ifr0edt0ii0o7ol.apps.googleusercontent.com',
    iosBundleId: 'com.example.assignment3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsNsurUFowQuuaakmKzoxzLVFoeJyHi-E',
    appId: '1:943448413343:ios:77cacd2475071c5afbfeaa',
    messagingSenderId: '943448413343',
    projectId: 'assignment-3-641c4',
    storageBucket: 'assignment-3-641c4.appspot.com',
    iosClientId: '943448413343-e3c5gq21tllbil1moh99miuqivphfv24.apps.googleusercontent.com',
    iosBundleId: 'com.example.assignment3.RunnerTests',
  );
}
